### ISSUE TITLE
Vendor not publishing the config file

### ISSUE THREAD

**Issue by opqclick** [ariaieboy/laravel-safe-browsing#2]
php artisan vendor:publish --tag="laravel-safe-browsing" this returning "No publishable resources for tag [laravel-safe-browsing"

**Comment by ariaieboy** [comment]
we used spatie package tool and in their package they remove laravel- from the package tags and adding a -config for publishing the config so you need use `php artisan vendor:publish --tag="safe-browsing-config"`
i've updated the package readme thanks for your report

**Comment by opqclick** [comment]
Got it. Thank you too for responding so quick!
